# Generated by Django 4.0.5 on 2022-06-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_sensor_device_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorvalue',
            name='humidity',
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_id',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
