# Generated by Django 4.0.5 on 2022-06-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_sensorvalue_temperature_humidity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='humidity',
            old_name='humidity',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='temperature',
            new_name='value',
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
