# Generated by Django 4.0.5 on 2022-06-20 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_humidity_time_alter_temperature_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humidity',
            name='time',
        ),
        migrations.RemoveField(
            model_name='temperature',
            name='time',
        ),
        migrations.AddField(
            model_name='humidity',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperature',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
