# Generated by Django 4.0.5 on 2022-06-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_humidity_time_remove_temperature_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='room',
            field=models.CharField(default='bath', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='type',
            field=models.CharField(default='temperature', max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
