version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

  mosquitto:
       image: toke/mosquitto
       network_mode: bridge
       container_name: mosquitto
       expose:
         - 1883
       ports:
         - 1883:1883
       restart: unless-stopped

  backend:
        build: ./backend
        ports:
          - 8000:8000
        volumes:
        - ./backend/sensor_backend:/app/sensor_backend
        depends_on:
         - mosquitto
