version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
  mqtt:
        image: toke/mosquitto
        network_mode: bridge
        container_name: mqtt
        expose:
          - 1883
        ports:
          - 1883:1883
        restart: unless-stopped
