version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true

    depends_on:
      - backend

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    expose:
      - 1883
    ports:
      - 1883:1883
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend/sensor_backend:/app/sensor_backend
    depends_on:
      - mosquitto

  db:
    image: postgres:13
    volumes:
      - ./db:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./env/postgres.env
